In [1]:
import pandas as pd
import numpy as np

In [2]:
data = {
    "name": ["Ahnaf", "Rahim", "Karim", "Sadia"],
    "age": [21, 22, 20, 23],
    "city": ["Dhaka", "Chittagong", "Sylhet", "Rajshahi"],
    "salary": [25000, 30000, 22000, 28000]
}
df = pd.DataFrame(data)
df

    name  age        city  salary
0  Ahnaf   21       Dhaka   25000
1  Rahim   22  Chittagong   30000
2  Karim   20      Sylhet   22000
3  Sadia   23    Rajshahi   28000

In [3]:
dataList = [
    ["Ahnaf", 21, "Dhaka", 25000],
    ["Rahim", 22, "Chittagong", 30000],
    ["Karim", 20, "Sylhet", 22000],
    ["Sadia", 23, "Rajshahi", 28000]
]
columns = ["name", "age", "city", "salary"]
df2 = pd.DataFrame(dataList, columns=columns)

In [4]:
df2['city']

0         Dhaka
1    Chittagong
2        Sylhet
3      Rajshahi
Name: city, dtype: str

In [5]:
df2[['name','age']]

    name  age
0  Ahnaf   21
1  Rahim   22
2  Karim   20
3  Sadia   23

In [6]:
df2["designation"] = ["Doctor",'Eng.',"doctor",'eng. ']
df2

    name  age        city  salary designation
0  Ahnaf   21       Dhaka   25000      Doctor
1  Rahim   22  Chittagong   30000        Eng.
2  Karim   20      Sylhet   22000      doctor
3  Sadia   23    Rajshahi   28000       eng.

In [7]:
df2.drop('city',axis=1)

    name  age  salary designation
0  Ahnaf   21   25000      Doctor
1  Rahim   22   30000        Eng.
2  Karim   20   22000      doctor
3  Sadia   23   28000       eng.

In [8]:
df2

    name  age        city  salary designation
0  Ahnaf   21       Dhaka   25000      Doctor
1  Rahim   22  Chittagong   30000        Eng.
2  Karim   20      Sylhet   22000      doctor
3  Sadia   23    Rajshahi   28000       eng.

In [9]:
df2.loc[[0,1]][["city","salary"]]

         city  salary
0       Dhaka   25000
1  Chittagong   30000

In [10]:
#only people with whose age is above 21
df2[df2["age"] > 21]

    name  age        city  salary designation
1  Rahim   22  Chittagong   30000        Eng.
3  Sadia   23    Rajshahi   28000       eng.

In [11]:
df2[(df2["age"] > 20) & (df2["city"] == 'Dhaka')] #20 age and dhakai thake

    name  age   city  salary designation
0  Ahnaf   21  Dhaka   25000      Doctor