In [55]:
import numpy as np
import pandas as pd

In [56]:
data = {
    "emp_id": [101, 102, 103, 104, 105, 106],
    "name": ["Ahnaf", "Rahim", "Karim", "Sadia", "Nusrat", "Tanvir"],
    "department": ["IT", "HR", "CS", "Finance", "IT", "EEE"],   
}
data2 = {
    "emp_id": [101, 102, 103, 104, 107, 108],
    "salary": [50000, 46000, 48000, 61000, 53000, 70000],
    "bonus": [5000, 4000, 3000, 6000, 4500, 8000]
}
df = pd.DataFrame(data)
df2 = pd.DataFrame(data2)

In [57]:
df

   emp_id    name department
0     101   Ahnaf         IT
1     102   Rahim         HR
2     103   Karim         CS
3     104   Sadia    Finance
4     105  Nusrat         IT
5     106  Tanvir        EEE

In [58]:
df2

   emp_id  salary  bonus
0     101   50000   5000
1     102   46000   4000
2     103   48000   3000
3     104   61000   6000
4     107   53000   4500
5     108   70000   8000

In [59]:
pd.merge(df,df2,on="emp_id",how= 'inner' )

   emp_id   name department  salary  bonus
0     101  Ahnaf         IT   50000   5000
1     102  Rahim         HR   46000   4000
2     103  Karim         CS   48000   3000
3     104  Sadia    Finance   61000   6000

In [60]:
pd.merge(df,df2,on="emp_id",how= 'outer' )

   emp_id    name department   salary   bonus
0     101   Ahnaf         IT  50000.0  5000.0
1     102   Rahim         HR  46000.0  4000.0
2     103   Karim         CS  48000.0  3000.0
3     104   Sadia    Finance  61000.0  6000.0
4     105  Nusrat         IT      NaN     NaN
5     106  Tanvir        EEE      NaN     NaN
6     107     NaN        NaN  53000.0  4500.0
7     108     NaN        NaN  70000.0  8000.0

In [61]:
pd.merge(df,df2,on="emp_id",how= 'left')

   emp_id    name department   salary   bonus
0     101   Ahnaf         IT  50000.0  5000.0
1     102   Rahim         HR  46000.0  4000.0
2     103   Karim         CS  48000.0  3000.0
3     104   Sadia    Finance  61000.0  6000.0
4     105  Nusrat         IT      NaN     NaN
5     106  Tanvir        EEE      NaN     NaN

In [62]:
pd.merge(df,df2,on="emp_id",how= 'right')

   emp_id   name department  salary  bonus
0     101  Ahnaf         IT   50000   5000
1     102  Rahim         HR   46000   4000
2     103  Karim         CS   48000   3000
3     104  Sadia    Finance   61000   6000
4     107    NaN        NaN   53000   4500
5     108    NaN        NaN   70000   8000

In [63]:
#concatination
df1 = pd.DataFrame({
    'A': ['A0', 'A1', 'A2'],
    'B': ['B0', 'B1', 'B2'],
    'C': ['C0', 'C1', 'C2']
})

df2 = pd.DataFrame({
    'A': ['A3', 'A4', 'A5'],
    'B': ['B3', 'B4', 'B5'],
    'C': ['C3', 'C4', 'C5']
})

In [64]:
df1

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [65]:
df2

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [66]:
pd.concat([df1,df2])

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [67]:
pd.concat([df1,df2],axis=1)

    A   B   C   A   B   C
0  A0  B0  C0  A3  B3  C3
1  A1  B1  C1  A4  B4  C4
2  A2  B2  C2  A5  B5  C5

In [68]:
#joining data frames

# First DataFrame
df1 = pd.DataFrame({
    'name': ['Alice', 'Bob', 'Charlie']
}, index=[1, 2, 3])

# Second DataFrame
df2 = pd.DataFrame({
    'score': [85, 90, 75]
}, index=[2, 3, 4])

In [69]:
df1

      name
1    Alice
2      Bob
3  Charlie

In [70]:
df2

   score
2     85
3     90
4     75

In [75]:
df1.join(df2)

      name  score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0

In [76]:
df2.join(df1)

   score     name
2     85      Bob
3     90  Charlie
4     75      NaN